# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - ln -s $PWD/gae_lib.pth $(python -c 'import sys; import os; print(os.path.join(sys.prefix, "lib", "python" + sys.version[:3], "site-packages"))')
  - pip install -t lib -r requirements_gae.txt
  - pip install -r requirements_local.txt
  - pip install tox

# command to run tests, e.g. python setup.py test
script: tox
